issues-3: Add menu style
hlxsites/durysta pull request #17
Opened 2023-06-13 15:54 UTC by QuentinVecchio

This PR introduces the menu style. Animation will come in a follow-up PR.

Part of #3 

Test URLs:
- Before: https://main--durysta--hlxsites.hlx.page
- After: https://3-header--durysta--hlxsites.hlx.page/

2023-06-13 20:35 UTC, kmurugulla requested changes

2023-06-13 20:35 UTC, kmurugulla commented on blocks/header/header.css
> +  background: #377e0b;
would be great if we could use the global variables defined in styles.css

2023-06-13 20:35 UTC, kmurugulla commented on blocks/header/header.css
> +  font-family: 'ITC Avant Garde Gothic W01 Md', var(--body-font-family);
duplicate declaration

2023-06-13 20:35 UTC, kmurugulla commented on blocks/header/header.css
> +  color: #3a423b;
use of variables :) please

2023-06-21 18:16 UTC, kmurugulla commented
@QuentinVecchio  - The header looks great . npm run lint would help with resolving CSS / JS lint issues locally before pushing the code :)

2023-06-22 08:11 UTC, QuentinVecchio commented on blocks/header/header.css
> +  background: #377e0b;
Using global variables now

2023-06-22 08:12 UTC, QuentinVecchio commented
> @QuentinVecchio - The header looks great 🥇 . npm run lint would help with resolving CSS / JS lint issues locally before pushing the code

Sorry it was a push before going home operation :)

Now the PR is ready for review and the linter should be good

2023-06-22 16:53 UTC, kmurugulla approved these changes

2023-06-22 16:53 UTC, merged